Add friends likes FZ
ACKAPOB/java-filmorate pull request #3
Opened 2022-07-14 08:26 UTC by ACKAPOB

2022-07-14 18:26 UTC, EugeneLenkevich requested changes
Привет,  Игорь, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-07-15 12:33 UTC, ACKAPOB commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return null;
Реализовал методы для User и Film

2022-07-16 04:21 UTC, eugene-lenkevich commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerIT.java
> +        // Тут костыль какой-то, сначала делаю два Post, может можно это в один response как то уложить?
Единственное, далее ассерт уже можно не делать, получается что проверка статуса делается два раза, но это мелочи :)

![image](https://user-images.githubusercontent.com/94845100/179339174-eef732ff-45ff-4f17-81b1-4fd569a3bd3f.png)

2022-07-16 04:21 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-08-09 07:12 UTC, merged